name: Create Automated PRs
on:
  push:
    branches:
    - 'nightly-**'
    paths:
    - 'summary/**'
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create pull request for new summary
      shell: bash
      run: |
        curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
        bin/hub pull-request -m '[Automated] Update summary csv files'
      env:
        GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
